### ISSUE TITLE
 cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by JohyC** [aoyouer/gocapture#1]
大佬求助！
Win10能够正常使用；
armv7l 架构linux 无法运行！
我想把这个go程序跑在我的小机器上面！
gocapture-cli v1.1-cli 版本！
另外请问一下大佬！有计划把文档写的更加详细点吗？🤣

**Comment by haojie06** [comment]
因为我只编译了amd64架构的版本，白天我试着编译一下arm架构的版本。然后现在这个程序还是相当初始的版本，没什么功能，所以文档比较简洁，过段时间我有时间的时候会进一步完善的，到时候应该会有更多的功能和详细一些的文档。

**Comment by JohyC** [comment]
> 因为我只编译了amd64架构的版本，白天我试着编译一下arm架构的版本。然后现在这个程序还是相当初始的版本，没什么功能，所以文档比较简洁，过段时间我有时间的时候会进一步完善的，到时候应该会有更多的功能和详细一些的文档。

期待大佬新版本！这个项目很棒！可视化及轻量的特性，很适合部署小机器上面！

**Comment by haojie06** [comment]
我编译了arm架构的版本，你可以试试看，有什么建议或者问题再回复吧。

**Comment by JohyC** [comment]
> 我编译了arm架构的版本，你可以试试看，有什么建议或者问题再回复吧。

能请教一下golang如何编译适合自己架构的版本吗？大佬编译的arm架构版本我还是跑不起来。🤣我的需求可能太小众了！（linux 的make和cmake了解更多一些！golang的编译我还需要更多的学习！）

源码运行报错 
![image](https://user-images.githubusercontent.com/38210128/121769446-36cefd80-cb96-11eb-8a5d-d50837f51533.png)
![image](https://user-images.githubusercontent.com/38210128/121769330-8f51cb00-cb95-11eb-8581-d77695a80c29.png)

**Comment by haojie06** [comment]
release里面的两个版本都试过了吗，运行前先chmod a+x 看看？不能运行提示是什么呢？

**Comment by JohyC** [comment]
> release里面的两个版本都试过了吗，运行前先chmod a+x 看看？不能运行提示是什么呢？

两个版本都有试过！🤣 
![image](https://user-images.githubusercontent.com/38210128/121772416-da74d980-cba7-11eb-8019-6ebbcd610812.png)

**Comment by aoyouer** [comment]
今天白天我再看看吧

**Comment by aoyouer** [comment]
arm版本显示No such file是因为找不到动态链接库，今天更新的版本改成静态链接了，你可以试试。

**Comment by haojie06** [comment]
> > release里面的两个版本都试过了吗，运行前先chmod a+x 看看？不能运行提示是什么呢？
> 
> 两个版本都有试过！🤣
> ![image](https://user-images.githubusercontent.com/38210128/121772416-da74d980-cba7-11eb-8019-6ebbcd610812.png)

arm版本显示No such file是因为找不到动态链接库，今天更新的版本改成静态链接了，你可以试试。
