### ISSUE TITLE
arm gocapture v1.1.1 版本报错无法分配内存！gocapturecli v1.1.1可以正常使用！

### ISSUE THREAD

**Issue by JohyC** [aoyouer/gocapture#2]
arm 的cli版本使用没有任何问题！非常完美！功能更强大的gocapture v1.1.1报错如下！Linux权限和内存我这边检查了。
麻烦大佬了！
![image](https://user-images.githubusercontent.com/38210128/122513283-cbc17300-d03c-11eb-9dad-d130a875568f.png)
![image](https://user-images.githubusercontent.com/38210128/122513646-412d4380-d03d-11eb-9157-1415012a10da.png)

**Comment by haojie06** [comment]
你这台机器的内存是多少的呀，还有是否开启了swap呢？是每次运行都会出现这个错误吗？我怀疑我程序有写的不合适的地方，占用了太多内存。你试试`sysctl -w vm.overcommit_memory=1 `后再运行程序。

**Comment by JohyC** [comment]
> 你这台机器的内存是多少的呀，还有是否开启了swap呢？是每次运行都会出现这个错误吗？我怀疑我程序有写的不合适的地方，占用了太多内存。你试试`sysctl -w vm.overcommit_memory=1 `后再运行程序。

机器是1g的内存，3g的swap内存；每次运行都会出现报错，htop中没有发现内存使用的迹象。sysctl -w vm.overcommit_memory=1 使用之后也是同样如此。。
![image](https://user-images.githubusercontent.com/38210128/122545744-c544f280-d060-11eb-88b5-68f19350a576.png)

**Comment by haojie06** [comment]
我犯了一个低级错误，在v1.1.2中修复了，你试试看。

**Comment by JohyC** [comment]
> 我犯了一个低级错误，在v1.1.2中修复了，你试试看。

可以了！非常完美！资源占用也是很低的！我还有一个小问题，这个项目地图用的什么坐标系呀？

**Comment by haojie06** [comment]
你是想修改显示的坐标吗？在static/js/config.js 里面可以修改所在城市以及经纬度。

**Comment by JohyC** [comment]
> 你是想修改显示的坐标吗？在static/js/config.js 里面可以修改所在城市以及经纬度。

我不知道项目用的什么坐标系，无法确定我这里的经纬度。
此外，我运行了gocapture大概三个小时后，gocapture就奔溃了。下面是奔溃的报告信息。
目前正在看项目的源码，我想尝试把项目通信方式改为websocket。（感觉setInterval定时请求数据的方式不太优雅。）

[golang报错.txt](https://github.com/aoyouer/gocapture/files/6678590/golang.txt)

**Comment by haojie06** [comment]
这个报错我倒是第一次见，websocket的话，现在这个web界面只是写出来测试的，我也有之后重写并改用websocket的计划

**Comment by JohyC** [comment]
> 这个报错我倒是第一次见，websocket的话，现在这个web界面只是写出来测试的，我也有之后重写并改用websocket的计划

第一次接触golang，语法都不太会。改起来太费劲了。。👨‍💻

**Comment by haojie06** [comment]
过段时间我就会加上的😊，不过先看看再运行，会不会过一会又出错

**Comment by JohyC** [comment]
> 过段时间我就会加上的😊，不过先看看再运行，会不会过一会又出错

😴可以的！

**Comment by haojie06** [comment]
我在我树莓派上运行了一段时间，不过没出现这个错误。另外我把数据更新方式改成websocket了，之后考虑重新写一个正式一点的前端。
